#!/usr/bin/env bash
# Install nginx
# Nginx should be listening on port 80
# Start the server

sudo apt update
sudo apt -y install nginx
sudo chown -R $USER:$USER /var/www/html
echo 'Hello World!' > /var/www/html/index.html
sudo chown -R root:root /var/www/html
sudo service nginx restart
