#!/usr/bin/env bash
# Install nginx
# Nginx should be listening on port 80
# Start the server

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
