#!/usr/bin/env bash
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# ping command usage
if [ "$1" ]; then
    ping -c 5 "$1"
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
