#!/usr/bin/env bash
# This script extracts and displays username, user ID, and home directory from /etc/passwd.

FILE="/etc/passwd"

while read -r line
do
	echo -e "${line}" | cut -d ":" -f1,3,6
done < $FILE

