#!/usr/bin/env bash
# This script tells the story of the users in /etc/passwd.

FILE="/etc/passwd"

while IFS=":" read -r username _ userid _ _ homedir shell
do
    # Extract the comment (GECOS) field, if available
    gecos=$(getent passwd "$username" | cut -d: -f5)

    echo "The user $username is part of the $userid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $gecos"
done < "$FILE"

