#!/usr/bin/env bash
# install ufw firewall & set requirements

# update
sudo apt-get -y update

# install UFW if not already installed
sudo apt-get -y install ufw

# enable UFW
sudo ufw disable

# set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# system stop ufw
sudo systemctl stop ufw

# allow specific ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# enable UFW to start enforcing these rules
sudo ufw enable

# check the status
sudo ufw status

